{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kijo.fullname" . }}
  labels:
    {{- include "kijo.labels" . | nindent 4 }}
rules:
  # Trivy Operator CRDs
  - apiGroups: ["aquasecurity.github.io"]
    resources:
      - vulnerabilityreports
      - clustervulnerabilityreports
      - configauditreports
      - clusterconfigauditreports
      - rbacassessmentreports
      - clusterrbacassessmentreports
      - infraassessmentreports
      - clusterinfraassessmentreports
      - exposedsecretreports
      - sbomreports
      - clustersbomreports
      - clustercompliancereports
    verbs: ["get", "list", "watch"]
  # Core resources for exposure analysis and cluster inventory
  - apiGroups: [""]
    resources: ["services", "pods", "namespaces", "nodes", "serviceaccounts"]
    verbs: ["get", "list"]
  # RBAC resources for security analysis
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings", "clusterrolebindings"]
    verbs: ["get", "list"]
  # Workload resources for inventory
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "statefulsets", "replicasets"]
    verbs: ["get", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gateways", "httproutes", "grpcroutes", "tcproutes", "tlsroutes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kijo.fullname" . }}
  labels:
    {{- include "kijo.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kijo.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kijo.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
